version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=n3xtcl0ud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      networks:
       -web

  app:
    image: nextcloud
    ports:
      - 8080:80
    networks:
    -web
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    labels:
   - traefik.backend=nextcloud
   - traefik.frontend.rule=Host:nextcloud.jsbjr.digital
   - traefik.port=80
   - traefik.docker.network=web
    restart: always
   
networks:
   web:
